# Análise Exploratória de Dados / Exploratory Data Analysis (EDA)

Uma boa EDA (Exploratory Data Analysis) pode ser pensada como uma sequência de perguntas que você faz ao dataset antes de partir para conclusões, visualizações mais sofisticadas ou Machine Learning.

- Um analista de dados é como um detetive: observa as pistas, encontra padrões e desvenda o que está por trás dos números.
- Dados são pistas. Padrões são evidências. E você é quem vai solucionar o mistério.
- Você não precisa de uma lupa para ser investigador — basta saber fazer as perguntas certas aos dados.


**Nos tempos dos reis, o conselheiro trazia informações para ajudar o governante a decidir. Hoje, o analista faz isso com dados. O rei tinha seus conselheiros. Hoje, empresas e organizações têm analistas de dados: pessoas que transformam informações em decisões.**

**Um analista de dados é como o conselheiro de um rei: transforma informações em conhecimento para orientar decisões importantes.**

# 0. Vamos começar. Primeiro importe pandas e os dados.

In [1]:
import pandas as pd

In [8]:
# Leia seu arquivo csv aqui

# df = pd.read_csv()

df = pd.read_csv('Stardew_valley_NPCs - Sheet1 (1).csv')
df

,Name,Gender,Birthday Season,Favorite Gifts Season,Marriage Candidate,Heart Events
0,Alex,Male,Summer,Fall,Yes,8
1,Elliot,Male,Fall,Fall,Yes,7
2,Harvey,Male,Winter,Fall,Yes,7
3,Sam,Male,Summer,Summer,Yes,8
4,Sebastian,Male,Winter,Fall,Yes,7
5,Shane,Male,Spring,Summer,Yes,12
6,Abigail,Female,Fall,Summer,Yes,8
7,Emily,Female,Spring,Fall,Yes,10
8,Haley,Female,Spring,Summer,Yes,7
9,Leah,Female,Winter,Spring,Yes,10
10,Maru,Female,Summer,Spring,Yes,7
11,Penny,Female,Fall,Summer,Yes,7
12,Caroline,Female,Winter,Summer,No,5
13,Clint,Male,Winter,Spring,No,5
14,Demetrius,Male,Summer,Spring,No,4
15,Dwarf,NaN,Summer,Winter,No,1
16,Evelyn,Female,Winter,Fall,No,3
17,George,Male,Fall,Spring,No,4
18,Gus,Male,Summer,Summer,No,5
19,Jas,Female,Summer,Fall,No,1
20,Jodi,Female,Fall,Fall,No,5
21,Kent,Male,Spring,Spring,No,4
22,Krobus,NaN,Winter,Fall,No,2
23,Leo,Male,Summer,Summer,No,6
24,Lewis,Male,Spring,Fall,No,4
25,Linus,Male,Winter,Spring,No,6
26,Marnie,Female,Fall,Summer,No,5
27,Pam,Female,Spring,Spring,No,4
28,Pierre,Male,Spring,Winter,No,3
29,Robin,Female,Fall,Summer,No,3
30,Sandy,Female,Fall,Winter,No,2
31,Vincent,Male,Spring,Fall,No,1
32,Willy,Male,Summer,Fall,No,5
33,Wizard,Male,Winter,Summer,No,2
34,Birdie,Female,NaN,NaN,No,0
35,Bouncer,Male,NaN,NaN,No,0
36,Gil,Male,NaN,NaN,No,0
37,Governor,Male,NaN,NaN,No,0
38,Grandpa,Male,NaN,NaN,No,0
39,Gunther,Male,NaN,NaN,No,0
40,Henchman,NaN,NaN,NaN,No,0
41,Marlon,Male,NaN,NaN,No,0
42,Morris,Male,NaN,NaN,No,0
43,Mr. Qi,Male,NaN,NaN,No,0
44,Professor Snail,Male,NaN,NaN,No,0

#### O próximo passo é dividir o processo em etapas

## 1. Entendimento geral do dataset

In [7]:
df.head()

,Name,Gender,Birthday Season,Favorite Gifts Season,Marriage Candidate,Heart Events
0,Alex,Male,Summer,Fall,Yes,8
1,Elliot,Male,Fall,Fall,Yes,7
2,Harvey,Male,Winter,Fall,Yes,7
3,Sam,Male,Summer,Summer,Yes,8
4,Sebastian,Male,Winter,Fall,Yes,7

Antes de analisar os dados, descubra o que você recebeu.

### Qual é a unidade de observação? Uma pessoa? Uma venda? Um crime? Um dia?

A unidade observada fala sobre personagens do jogo Stardew Valley.

### Qual é a origem dos dados?

O jogo Stardew Valley.

### Quantas linhas e colunas existem?

In [27]:
total_linhas = df.shape[0]
total_colunas = df.shape[1]

print(f"A tabela possui {total_linhas} linhas e {total_colunas} colunas.")

A tabela possui 45 linhas e 6 colunas.

### O que cada coluna representa?

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   45 non-null     str
 1   Gender                 42 non-null     str
 2   Birthday Season        34 non-null     str
 3   Favorite Gifts Season  34 non-null     str
 4   Marriage Candidate     45 non-null     str
 5   Heart Events           45 non-null     int64
dtypes: int64(1), str(5)
memory usage: 3.2 KB

### Qual é o período coberto pelos dados?

In [ ]:
#nao existem dados de tempo neste arquivo.

### Existem identificadores únicos?

In [ ]:
#sim

### Existem colunas que parecem redundantes?

# 2. Tipos e estrutura das variáveis(colunas)

Para cada coluna:
- Ela é numérica, categórica, texto, data/hora ou booleana?
- O tipo armazenado corresponde ao tipo real da informação? Exemplo: Existem números armazenados como texto?
- Existem datas armazenadas como strings? 
- Existem categorias com grafias diferentes?
```text
    Exemplo:
    - "São Paulo"
    - "Sao Paulo"
    - "são paulo"
    Podem representar a mesma categoria.
```

In [28]:
df

,Name,Gender,Birthday Season,Favorite Gifts Season,Marriage Candidate,Heart Events
0,Alex,Male,Summer,Fall,Yes,8
1,Elliot,Male,Fall,Fall,Yes,7
2,Harvey,Male,Winter,Fall,Yes,7
3,Sam,Male,Summer,Summer,Yes,8
4,Sebastian,Male,Winter,Fall,Yes,7
5,Shane,Male,Spring,Summer,Yes,12
6,Abigail,Female,Fall,Summer,Yes,8
7,Emily,Female,Spring,Fall,Yes,10
8,Haley,Female,Spring,Summer,Yes,7
9,Leah,Female,Winter,Spring,Yes,10
10,Maru,Female,Summer,Spring,Yes,7
11,Penny,Female,Fall,Summer,Yes,7
12,Caroline,Female,Winter,Summer,No,5
13,Clint,Male,Winter,Spring,No,5
14,Demetrius,Male,Summer,Spring,No,4
15,Dwarf,NaN,Summer,Winter,No,1
16,Evelyn,Female,Winter,Fall,No,3
17,George,Male,Fall,Spring,No,4
18,Gus,Male,Summer,Summer,No,5
19,Jas,Female,Summer,Fall,No,1
20,Jodi,Female,Fall,Fall,No,5
21,Kent,Male,Spring,Spring,No,4
22,Krobus,NaN,Winter,Fall,No,2
23,Leo,Male,Summer,Summer,No,6
24,Lewis,Male,Spring,Fall,No,4
25,Linus,Male,Winter,Spring,No,6
26,Marnie,Female,Fall,Summer,No,5
27,Pam,Female,Spring,Spring,No,4
28,Pierre,Male,Spring,Winter,No,3
29,Robin,Female,Fall,Summer,No,3
30,Sandy,Female,Fall,Winter,No,2
31,Vincent,Male,Spring,Fall,No,1
32,Willy,Male,Summer,Fall,No,5
33,Wizard,Male,Winter,Summer,No,2
34,Birdie,Female,NaN,NaN,No,0
35,Bouncer,Male,NaN,NaN,No,0
36,Gil,Male,NaN,NaN,No,0
37,Governor,Male,NaN,NaN,No,0
38,Grandpa,Male,NaN,NaN,No,0
39,Gunther,Male,NaN,NaN,No,0
40,Henchman,NaN,NaN,NaN,No,0
41,Marlon,Male,NaN,NaN,No,0
42,Morris,Male,NaN,NaN,No,0
43,Mr. Qi,Male,NaN,NaN,No,0
44,Professor Snail,Male,NaN,NaN,No,0

# 3. Dados ausentes

Uma das perguntas mais importantes:

- Onde estão os dados faltantes e por que estão faltando?

### Existem valores NaN? Quantos por coluna?

dica: df.isna().sum()

In [12]:
df.isna().sum()

Name                      0
Gender                    3
Birthday Season          11
Favorite Gifts Season    11
Marriage Candidate        0
Heart Events              0
dtype: int64

### Qual percentual representa? Existem linhas completamente vazias?

dica: (df.isna().mean() * 100).sort_values(ascending=False)

In [13]:
(df.isna().mean()*100).sort_values(ascending=False)

Favorite Gifts Season    24.444444
Birthday Season          24.444444
Gender                    6.666667
Name                      0.000000
Marriage Candidate        0.000000
Heart Events              0.000000
dtype: float64

# 4. Duplicidades

Pergunte:

- Existem linhas duplicadas?
- Existem registros duplicados pelo identificador que deveria ser único?
- O que define uma observação como única?
- Duplicatas são erros ou representam eventos legítimos?

dica: df.duplicated().sum()

In [14]:
df.duplicated().sum()

np.int64(0)

# 5.Qualidade e consistência dos dados

Aqui é uma etapa extremamente importante.

Aqui você começa a procurar anomalias.

Perguntas:

- Existem valores impossíveis?
- Existem valores negativos onde não deveriam existir?
- Existem idades de 300 anos?
- Existem datas futuras?
- Existem categorias inesperadas?
- Existem valores 0 que deveriam ser NaN?
- Existem erros de digitação?
- Existem unidades diferentes misturadas?

Exemplo:
```text
idade
-----
21
35
42
-5
999

Ou:

salário
-------
0
3500
4200
-600
5000
3500000


```
**A pergunta não é simplesmente:**

"Esse valor é diferente?"

Mas:

"Esse valor faz sentido dentro do contexto do problema?"

# 6. Distribuição das variáveis numéricas

Para cada variável numérica:

- Qual é o mínimo?
- Qual é o máximo?
- Qual é a média?

In [ ]:
df['Heart Events'].mean() #media

np.float64(3.9555555555555557)

In [ ]:
df['Heart Events'].max() #maximo

np.int64(12)

In [ ]:
df['Heart Events'].min() #minimo

np.int64(0)

# 7. Distribuição das variáveis categóricas

Para cada variável categórica:

- Quais categorias existem?
- Quantas observações existem em cada categoria?
- Qual é a categoria mais frequente?
- Existem categorias muito raras?
- Existe desbalanceamento?
- Existem categorias inesperadas?

Perguntas importantes:

Existe uma categoria responsável por 90% dos registros?

Existem categorias com apenas 1 ou 2 observações?

Isso pode ser extremamente importante posteriormente.

# 8. Perguntas específicas do domínio

Essa é talvez a parte mais importante.

Você precisa perguntar:

O que é importante nesse problema específico?

Por exemplo:

**Dataset de vendas**

- Qual produto vende mais?
- Qual região vende mais?
- Quando as vendas aumentam?
- Qual produto possui maior faturamento?


**Dataset de crimes**

- Onde ocorrem mais ocorrências?
- Quando ocorrem?
- Quais naturezas predominam?
- Existem diferenças entre bairros?
- Existe concentração geográfica?

**Dataset de estudantes**

- Existe relação entre frequência e nota?
- Quais fatores estão associados à evasão?
- Como as notas variam entre turmas?
- Existe diferença por período?

**Dataset financeiro**

- Como o faturamento evolui?
- Quais produtos geram maior margem de lucro?
- Existem transações anormais?
- Existem valores extremos?

In [ ]:
df[df['Heart Events'] == df['Heart Events'].max()]['Name'].values[0]

#personagem com maior quantidade de Heart Events.

'Shane'

In [ ]:
df[df['Heart Events'] == df['Heart Events'].min()]['Name'].values[0]

#personagem com menor quantidade de Heart Events

'Birdie'